openapi: 3.1.0
info:
  version: 1.0.0
  title: Water Tracker App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation
tags:
  - name: Auth
    description: Auth operations.
  - name: Users
    description: Users operations.
  - name: Water
    description: Water operations.
servers:
  - url: http://localhost:3000
  - url: https://watertrackerbackend-1b9z.onrender.com
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /users/curent:
    get:
      $ref: ../swagger/paths/users/curent.yaml
  /users/{id}:
    get:
      $ref: ../swagger/paths/users/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/users/{id}/patch.yaml
  /users/waterRate/{id}:
    patch:
      $ref: ../swagger/paths/users/{id}/patchWaterRate.yaml
  /users/avatar/{id}:
    patch:
      $ref: ../swagger/paths/users/{id}/patchAvatar.yaml
  /water/dayInfo/{todayStr}:
    get:
      $ref: ../swagger/paths/water/getDayInfo.yaml
  /water/monthInfo:
    get:
      $ref: ../swagger/paths/water/getMonthInfo.yaml
  /water:
    post:
      $ref: ../swagger/paths/water/post.yaml
  /water/{id}:
    patch:
      $ref: ../swagger/paths/water/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/water/{id}/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
