openapi: 3.1.0
info:
  version: 1.0.0
  title: app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation
tags:
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url:
paths:

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
